server:
  port: 9100

spring:
  application:
    name: config-server

##指定需要跟注册中心交互
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true